config/routes.rb
Rails.application.routes.draw do
  root 'translations#index'

  post 'translations', to: 'translations#create'
  get 'help', to: 'help#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/translation.rb
class Translation < ApplicationRecord
	mount_uploader :yml_file, TranslationUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/help_controller.rb
class HelpController < ApplicationController
  def index; end
end

app/controllers/translations_controller.rb
class TranslationsController < ApplicationController
  before_action :set_up_instance_variables
  before_action :get_submit_text, only: [:index]

  def index; end

  def create
  	# TODO: validate file type. yml only
  	# TODO: validate language code. use another method for that
  	if @translation.update(translation_params)
      translate(@translation)
  	else
  		flash[:alert] = "Something went wrong. Please try again."
  	end
  end

  private

  def set_up_instance_variables
    @translation = Translation.new
    @languages = EasyTranslate::LANGUAGES

    @languages.clone.each do |k, v|
      @languages[k] = v.titleize
    end
    @languages = @languages.invert
  end

  def translation_params
  	params.require(:translation).permit(:yml_file, :from, :to)
  end

  def translate(translation)
    translated = get_translation(translation)
    update_file(translated, translation)
    download_file(translation)
  end

  def get_translation(translation)
  	@text = get_translation_text(translation.yml_file)

  	EasyTranslate.api_key = ENV["GOOGLE_API_KEY"]
 		EasyTranslate.translate(@text, from: translation.from, to: translation.to)
  end

  def get_translation_text(file)
  	@text = []
  	yml_file = YAML.load(File.read(file.path))
  	def check_hash(value)
  		if value.is_a? Hash
  			value.each do |key, value|
  				check_hash(value)
  			end
  		else
  			@text.push value
  		end
  	end
  	
  	yml_file.each do |key, value|
  		check_hash(value)
  	end
  	@text
  end

  def update_file(translated, translation)
  	@yml_file = YAML.load(File.read(translation.yml_file.path))
  	@translated = translated
    @translation = translation

  	def check(k, v, parent = nil, pop = false)
      @i += "['#{k}']"
  		if v.is_a? Hash
  			v.clone.each do |_k, _v|
  				check(_k, _v, k, v.length > 1)
  			end
  		else 
  			eval("@yml_file#{@i} = @translated[@counter]")
        @counter += 1
  			
        if pop
          @i.slice! "['#{k}']"
          if eval("@yml_file#{@i}").to_a.last == [k,v]
            @i.slice! "['#{parent}']"
          end
        else
          @i = "['#{@translation.from}']"
        end
  		end
  	end

    @counter = 0
    @i = "['#{translation.from}']"
    @yml_file[translation.from].each do |k, v|
      check(k, v)
    end
    @yml_file[translation.to] = @yml_file.delete(translation.from)
    File.open(translation.yml_file.path, 'w') { |f| f.write(@yml_file.to_yaml) }
  end

  def download_file(translation)
    send_file(
      File.open(translation.yml_file.path, 'r'),
      filename: translation.yml_file.identifier,
      type: "application/x-yaml",
      disposition: 'attachment',
      status: 200
    )
  end

  def get_submit_text
    @submit_text = ['Abracadabra!', 'Hocus Pocus!', 'Presto chango!', 'Shazam!'].sample
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/help_helper.rb
module HelpHelper
end

app/helpers/translation_helper.rb
module TranslationHelper
end

app/views/help/index.html.erb
<div class='container'>
  <div class='w-100'>
		<div class='row my-3'>
			<div class='col-md-6 offset-md-3'>
				<h3>Help</h3>
				<hr class='w-100'>
				<p>
					Read this if you're interested in finding out 
					<span class='font-weight-semibold'>How to use Automated T10n</span>, or <span class='font-weight-semibold'>Why I'm building it</span>.
				</p>
			</div>
		</div>
		<div class='row mb-3'>
			<div class='col-md-6 offset-md-3'>
				<h5>How to use Automated T10n</h5>		
				<p>
					First, find yourself a <span class='font-weight-semibold'>.yml</span> file.
					It should contain all the keys & corresponding values you wish to translate from.
				</p>
				<p>
					Upload that file. Choose the language found in the file you've just uploaded.
					<span class='text-muted'>Note: The language code for this language should be the first key found in your file.</span>
				</p>
				<p>
					Then, find the language you'd like to have your keys be translated into from the <span class='font-italic'>extensive</span> list of languages provided.
				</p>
				<p>
					Hit that magical grey button- gently, please- & give us a moment for us to work our magic.
					Once we're done, we'll send the translated file straight to your browser.
				</p>
				<p>
					Hm. Easy, right? Yeah, it's pretty cool.
				</p>
			</div>
		</div>
		<div class='row mb-3'>
			<div class='col-md-6 offset-md-3'>
				<h5>Why I'm building Automated T10n</h5>	
				<p>
					Whenever I build something, it's a given that I'd like everyone to be able to experience it.
					I'd imagine this is a sentiment shared by most, if not all, people.
				</p>
				<p>
					However, in my recent endeavours to first internationalize, then also localize a non-trivial Rails application, I've noticed that it isn't an easy feat.
					There really isn't an easy, automated way to achieve this.
					That means that multi-language support <span class='font-weight-semibold'>just isn't attainable</span> from the get-go.
				</p>
				<p>
					The aim is to bring this ideal of localization, even in an application's early days, within reach.
				</p>
				<p>
					Build solutions that knows no language boundaries.
				</p>
			</div>
		</div>
		<div class='row mb-3'>
			<div class='col-md-6 offset-md-3'>
				<h5>More Resources</h5>
				<p>
					For clarity's sake, I've included several example .yml files that will be translated just fine in the GitHub repo. Find them <a href='https://github.com/shleen/Automated-T10n/tree/master/examples'>here</a>.
				</p>
			</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Automated T10n</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- jQuery -->
    <script type='text/javascript' scr='<%= asset_path("jquery-3.3.1.min.js") %>'></script>

    <!-- Bootstrap 4 assets -->
    <script type='text/javascript' src='<%= asset_path("bootstrap.min.js") %>'></script>
    <link rel='stylesheet' type='text/css' href='<%= asset_path("bootstrap.min.css") %>'>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/translations/index.html.erb
<div class='container h-100'>
  <div class='w-100'>
		<div class='row'>
			<div class='col-md-6 offset-md-3'>
				<h3 class='mb-0'>Automated T10n</h3>
				<span class='text-muted'>Quick, effortless, & everything you never knew you needed.</span>
				<hr class='w-100'>
			</div>
		</div>
		<%= form_for @translation, url: translations_path, multipart:true do |f| %>
		<div class='row'>
			<div class='col-md-6 offset-md-3'>
				<div class='form-group'>
					<%= f.label :yml_file, "File to translate (.yml only please)" %>
					<%= f.file_field :yml_file, class: 'form-control-file', required: 'required' %>
				</div>
				<div class='row'>
					<div class='col-md-6'>
						<div class='form-group'>
							<%= f.label :from, "Translate from:" %>
							<%= f.select :from, options_for_select(@languages, selected: 'en'), {}, { class:'form-control' } %>
						</div>
					</div>
					<div class='col-md-6'>
						<div class='form-group'>
							<%= f.label :to, "Translate to:" %>
							<%= f.select :to, options_for_select(@languages), {}, { class:'form-control' } %>
						</div>
					</div>
				</div>
				<div class='form-group'>
					<%= f.submit @submit_text, class:'btn btn-secondary w-100', data: { disable_with: false } %>
					<span class='small'>Need help? Check out the guide <%= link_to "here", help_path %>.
					</span>
				</div>
			</div>
		</div>
		<% end %>
	</div>
</div>